from pathlib import Path

from preflight.ai_reviewer import ReviewIssue


def generate_mock_report(path: Path, data: list[ReviewIssue], commit_hash: str, branch: str, project: str):
    """Generates a mock HTML report at the specified path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    html_content = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Preflight Review Results</title>
        <style>
            body { font-family: sans-serif; padding: 20px; }
            h1 { color: #333; }
            .issue { border: 1px solid #ccc; padding: 10px; margin-bottom: 10px; border-radius: 5px; }
            .severity-HIGH { border-left: 5px solid red; }
            .severity-MEDIUM { border-left: 5px solid orange; }
            .severity-LOW { border-left: 5px solid green; }
        </style>
    </head>
    <body>
        <h1>Preflight Review Results</h1>
        <p>This is a mock report generated by Preflight.</p>
        <div class="issue severity-HIGH">
            <h3>High Severity Issue</h3>
            <p>Description of the issue goes here.</p>
        </div>
        <div class="issue severity-MEDIUM">
            <h3>Medium Severity Issue</h3>
            <p>Description of the issue goes here.</p>
        </div>
    </body>
    </html>
    """
    path.write_text(html_content, encoding="utf-8")
